spring:
  config:
    activate:
      on-profile: c3p0
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
    jdbc-url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:enterprise;DB_CLOSE_DELAY=-1}
    user: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    initial-pool-size: 3
    min-pool-size: 3
    max-pool-size: 15
    max-idle-time: 300
app:
  datasource:
    pool: c3p0
